### ISSUE TITLE
No commands displayed when running `fnug` with a simple `.fnug.yaml` populated

### ISSUE THREAD

**Issue by ristomatti** [nickolaj-jepsen/fnug#1]
I found fnug through the [Terminal Trove](https://terminaltrove.com/fnug/) newsletter. It seems I got the (dis)honor to report the first issue.

I've installed `fnug` using `pipx install fnug`:

```
$ pipx list | grep fnug
   package fnug 0.0.22, installed using Python 3.12.3
    - fnug
```

I have created `.fnug.yaml` on a project folder with the following contents:

```yaml
fnug_version: 0.1.0
name: frontend
commmands:
  - name: tsc
    cmd: npm run tsc
  - name: lint
    cmd: npm run lint
  - name: test
    cmd: npm run test:ci
  - name: prettier
    cmd: npm run prettier
```

When running `fnug`, it opens it's TUI but it shows empty. Is there something missing from the config? fnug seems to detect the config file as it gave an error when I tried changing `fnug_version` to `0.0.22` as a test.

I'm running on a Ubuntu 20.04 based OS.

**Comment by nickolaj-jepsen** [comment]
Hi, sorry for the late response, and thanks for trying out fnug :slightly_smiling_face: 

Seems like you have a typo in the .fnug.yaml (`commmands` -> `commands`), this config should work:

```yaml
fnug_version: 0.1.0
name: frontend
commands:
  - name: tsc
    cmd: npm run tsc
  - name: lint
    cmd: npm run lint
  - name: test
    cmd: npm run test:ci
  - name: prettier
    cmd: npm run prettier
```

I've released a new version, which has a warning if you try to start fnug without any commands / command-groups registered, hopefully this makes it easier to figure out similar issues in the future.
